### ISSUE TITLE
Correct *.map files not found in path '/opt/wow/install/mangos/conf/maps'

### ISSUE THREAD

**Issue by ghost** [mangosthree/server#47]
I am trying to get this up and running in order to experiment with it. That being said I am unable to do so on Linux, as the map files expected differ from those extracted from the 4.3.4:15595 client.
I have followed the steps detailed in the [installation guide](https://www.getmangos.eu/wiki/documentation/installation-guides/guideslinux/installing-mangos-on-ubuntu-server-1804-r40005/), including database setup using the mangosthree/database repo.
The installation process including build and database population happens without problem, however when I get to the point of starting mangosd I get the following output;

```
$ ./mangosd 
2201001 [world-daemon]
<Ctrl-C> to stop.
  __  __      _  _  ___  ___  ___   _____ _         
 |  \/  |__ _| \| |/ __|/ _ \/ __| |_   _| |_  _ _ ___ ___    
 | |\/| / _` | .` | (_ | (_) \__ \   | | | ' \| '_/ -_) -_)  
 |_|  |_\__,_|_|\_|\___|\___/|___/   |_| |_||_|_| \___\___| 
 Powered By MaNGOS Core
 __________________________________________________________

 Website/Forum/Wiki/Issue Tracker: https://www.getmangos.eu
 __________________________________________________________


Using configuration file /opt/wow/install/mangos/conf/mangosd.conf.
Using SSL version: OpenSSL 1.1.1n  15 Mar 2022 (Library: OpenSSL 1.1.1n  15 Mar 2022)
Using ACE: 6.5.9
World Database total connections: 2
Connected to MySQL database root@127.0.0.1:3306/mangos3
MySQL client library: 10.3.34
MySQL server ver: 10.3.34-MariaDB-0+deb10u1 
AUTOCOMMIT SUCCESSFULLY SET TO 1
Connected to MySQL database root@127.0.0.1:3306/mangos3
MySQL client library: 10.3.34
MySQL server ver: 10.3.34-MariaDB-0+deb10u1 
AUTOCOMMIT SUCCESSFULLY SET TO 1
The table `db_version` indicates that your [World] database has the same version as the core requirements.

Character Database total connections: 2
Connected to MySQL database user@127.0.0.1:3306/character3
MySQL client library: 10.3.34
MySQL server ver: 10.3.34-MariaDB-0+deb10u1 
AUTOCOMMIT SUCCESSFULLY SET TO 1
Connected to MySQL database user@127.0.0.1:3306/character3
MySQL client library: 10.3.34
MySQL server ver: 10.3.34-MariaDB-0+deb10u1 
AUTOCOMMIT SUCCESSFULLY SET TO 1
The table `db_version` indicates that your [Character] database has the same version as the core requirements.

Login Database total connections: 2
Connected to MySQL database user@127.0.0.1:3306/realmd
MySQL client library: 10.3.34
MySQL server ver: 10.3.34-MariaDB-0+deb10u1 
AUTOCOMMIT SUCCESSFULLY SET TO 1
Connected to MySQL database user@127.0.0.1:3306/realmd
MySQL client library: 10.3.34
MySQL server ver: 10.3.34-MariaDB-0+deb10u1 
AUTOCOMMIT SUCCESSFULLY SET TO 1
The table `db_version` indicates that your [Realmd] database has the same version as the core requirements.


Realm running as realm ID 1

Using World DB: Version: 22, Structure: 2, Content: 10

Using DataDir /opt/wow/install/mangos/conf/
WORLD: VMap support included. LineOfSight:1, getHeight:1, indoorCheck:1
WORLD: VMap data directory is: /opt/wow/install/mangos/conf/vmaps
WORLD: MMap pathfinding enabled

Please check for the existence of map file '/opt/wow/install/mangos/conf/maps/00004331.map
'
Correct *.map files not found in path '/opt/wow/install/mangos/conf/maps' or *.vmtree/*.vmtile files in '/opt/wow/install/mangos/conf/vmaps'. Please place *.map and vmap files in appropriate directories or correct the DataDir value in the mangosd.conf file.
```

The map files were extracted using the `./bin/tools/map-extractor` binary obtained post build, and a 4.3.4:15595 client. The map files are in the expected directory, however the dump don't contain the file `00004331.map`.

Any idea what's going wrong? Thank you for all your hard work :)

**Comment by billy1arm** [comment]
@opzeta Something seems odd, we will have to investigate

**Comment by ghost** [comment]
Let me know if I can help in any way. When reviewing extracted maps from earlier versions of the client (3.3.5a) I noticed there was a `0004331.map` but I can't seem to find a `00004331.map`.

**Comment by timesorrow** [comment]
I have the exact same issue
actually, none of the clients would spit out this map name (it is 1 character longer than all other maps)
Where in the code is it checked?

**Comment by timesorrow** [comment]
did some checking of the source code which is used to load the server (and then the maps in particular):
in the GridMap.cpp, which I believe is used to load the maps, there is a hash that is used to looks for the file names, which looks like this:"maps/%04u%02u%02u.map").c_str(), mapid, gx, gy);" indicating that it is expecting an 8 digit filename + .map. Currently, the .map files for 4.3.4 are 7 digit maps. are we using the wrong map import in the GridMap.cpp?

**Comment by timesorrow** [comment]
this is where it goes wrong... 
https://github.com/mangosthree/server/commit/1ba32d2433475c1f88975c705fe9b0a698bb51af

**Comment by billy1arm** [comment]
@timesorrow I have asked Fyre to prepare a pr for me to attempt to fix this:
https://github.com/mangosthree/server/pull/57

**Comment by fuzionproject** [comment]
1-10	 Dun Morogh -id 1
 	1-10	 Durotar -id 14
 	1-10	 Elwynn Forest - id 12
 	1-10	 Mulgore -id 215
 	1-10	 Teldrassil -id 141
 	1-10	 Tirisfal Glades id -85
 	10-20	 Darkshore
 	10-20	 Loch Modan
 	10-20	 Silverpine Forest
 	10-20	 Westfall
 	10-25	 Barrens
 	15-25	 Redridge Mountains
 	15-27	 Stonetalon Mountains
 	18-30	 Ashenvale
 	18-30	 Duskwood
 	20-30	 Hillsbrad Foothills
 	20-30	 Wetlands
 	25-35	 Thousand Needles
 	30-40	 Alterac Mountains
 	30-40	 Arathi Highlands
 	30-40	 Desolace
 	30-45	 Stranglethorn Vale
 	35-45	 Dustwallow Marsh
 	35-45	 Badlands
 	35-45	 Swamp of Sorrows
 	40-50	 Feralas
 	40-50	 Hinterlands
 	40-50	 Tanaris
 	45-50	 Searing Gorge
 	45-55	 Azshara
 	45-55	 Blasted Lands
 	48-55	 Un'goro Crater
 	48-55	 Felwood
 	50-58	 Burning Steppes
 	51-58	 Western Plaguelands
 	53-60	 Eastern Plaguelands
 	53-60	 Winterspring
 	55-60	 Deadwind Pass
 	55-60	 Moonglade
 	55-60	 Silithus

 	https://mmo4ever.com/cataclysm/maps.php here cand find all ids of maps..i have put here the list with the maps and some ids the rest cant add it by your self ! after try to build again the tools to can have all maps

**Comment by billy1arm** [comment]
This is now resolved
