### ISSUE TITLE
[Problem] npc name unknown

### ISSUE THREAD

**Issue by xBarselonx** [mangosthree/server#68]
Hi!
Compiled yesterday and I ended up with:
 1. npc name "unknown"
2. The hunter's pet is not moving. Stands in place.
3. The npc has no gossip menu.
4. Selected talents do not apply.
5. Quit the game is not possible. Only ctrl + f4.
What could this be connected with? I use World of Warcraft client 4.3.4 (Build 15595). Maybe it's because I'm not patched wow.exe. (https://github.com/mangosthree/tools/tree/master/MaNGOSPatcher ).
I already had a patched wow.exe to log into the game, but only with a different connection_patcher patch from https://github.com/The-Cataclysm-Preservation-Project - I used it.

**Comment by billy1arm** [comment]
@xBarselonx - it could well be, we have just checked and using various clients we have that are patched - it's working correctly
