### ISSUE TITLE
Flying mount turns gm fly mode on

### ISSUE THREAD

**Issue by GiantCrocodile** [mangosthree/server#8]
If you use a flying mount the gm fly mode will be turned on even if you have gm level 0. It's impossible for the player to stop/deactivate the fly mode.

I don't know if this bug is related to the buggy riding and flying trainers.

**Comment by Morketh** [comment]
I have reproduced the results with both level 4 and level 0 accounts, after a brand new compile as of last night. also the bug didn't seem to "work" until AFTER purchasing the flight skills. not sure if that has anything to do with it but in programming some times any information is better then nothing to go on

**Comment by D3thw0lf** [comment]
maybe it's fixed ... this is a very old bug ;)

**Comment by billy1arm** [comment]
I am hoping to get this moving again in the next few months.

The new build system that is used in Zero, One and Two is currently being ported to Three.
- Then we'll be back on track

**Comment by GiantCrocodile** [comment]
@D3thw0lf it isn't fixed yet ;).
